// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetPass.Models;

namespace PetPass.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211024181844_M02")]
    partial class M02
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PetPass.Models.Pet", b =>
                {
                    b.Property<int>("IdPet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataNascPet")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRegPet")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoPet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("IdadePet")
                        .HasColumnType("float");

                    b.Property<string>("NomePet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PesoPet")
                        .HasColumnType("int");

                    b.Property<string>("RacaPet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SexoPet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoPet")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPet");

                    b.ToTable("MeusPets");
                });
#pragma warning restore 612, 618
        }
    }
}
